# Generated by Django 4.0.3 on 2022-03-30 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(max_length=255)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.building')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=255)),
                ('model_number', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.floor')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.office')),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=255)),
                ('model_number', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.floor')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.office')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.router')),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=255)),
                ('pc_name', models.CharField(max_length=255)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.switch')),
            ],
        ),
    ]
