# Generated by Django 4.0.3 on 2022-03-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='is_reachable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
